spring:
  datasource:
    url: jdbc:h2:mem:debbi
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2   # 控制台 http://localhost:8080/h2
